version: "3.7"
services:
  qdrant/qdrant:
    container_name: qdrant/qdrant
    image: qdrant/qdrant:v1.13.3
    restart: unless-stopped
    ports:
      - ${APP_PORT}:6333
      - 6334:6334
      - 6335:6335
    networks:
      - tipi_main_network
    enviroment:
      - TZ=${TZ}
    labels:
      # Main
      traefik.enable: false
      runtipi.managed: true
