services:
  transmission-vpn:
    image: haugene/transmission-openvpn:5.3.1
    container_name: transmission-vpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    dns:
      - ${DNS_IP}
    environment:
      - PUID=${TRANSMISSION_PUID-1000}
      - PGID=${TRANSMISSION_PGID-1000}
      - TZ=${TZ-Europe/Paris}
      - TRANSMISSION_RPC_PASSWORD=${TRANSMISSION_RPC_PASSWORD}
      - TRANSMISSION_RPC_USERNAME=${TRANSMISSION_RPC_USERNAME}
      - OPENVPN_PROVIDER=${TRANSMISSION_OVPN_PROVIDER-NORDVPN}
      - OPENVPN_CONFIG=${TRANSMISSION_OVPN_CONFIG}
      - OPENVPN_USERNAME=${TRANSMISSION_OVPN_USERNAME}
      - OPENVPN_PASSWORD=${TRANSMISSION_OVPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60 --pull-filter ignore ping
      - LOCAL_NETWORK=${TRANSMISSION_OVPN_LOCAL_NETWORK-10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      - TRANSMISSION_WEB_UI=${TRANSMISSION_WEBUI}
      - LOG_TO_STDOUT=true
      - GLOBAL_APPLY_PERMISSIONS=false
      - CREATE_TUN_DEVICE=${TRANSMISSION_CREATE_TUN_DEVICE-false}
      - PEER_DNS=${TRANSMISSION_PEER_DNS-false}
      
      # Basic Transmission Directories & Preallocation
      - TRANSMISSION_DOWNLOAD_DIR=${TRANSMISSION_DOWNLOAD_DIR-/media/torrents/complete}
      - TRANSMISSION_INCOMPLETE_DIR_ENABLED=${TRANSMISSION_INCOMPLETE_DIR_ENABLED-true}
      - TRANSMISSION_INCOMPLETE_DIR=${TRANSMISSION_INCOMPLETE_DIR-/media/torrents/incomplete}
      - TRANSMISSION_PREALLOCATION=${TRANSMISSION_PREALLOCATION-1}
      
      # Network & Peer Settings
      - TRANSMISSION_DHT_ENABLED=${TRANSMISSION_DHT_ENABLED-false}
      - TRANSMISSION_LPD_ENABLED=${TRANSMISSION_LPD_ENABLED-false}
      - TRANSMISSION_PEX_ENABLED=${TRANSMISSION_PEX_ENABLED-false}
      - TRANSMISSION_PEER_DNS=${TRANSMISSION_PEER_DNS-false}
      - TRANSMISSION_PEER_LIMIT_GLOBAL=${TRANSMISSION_PEER_LIMIT_GLOBAL-0}
      - TRANSMISSION_PEER_LIMIT_PER_TORRENT=${TRANSMISSION_PEER_LIMIT_PER_TORRENT-0}
      - TRANSMISSION_PEER_PORT=${TRANSMISSION_PEER_PORT-0}
      - TRANSMISSION_PEER_PORT_RANDOM_HIGH=${TRANSMISSION_PEER_PORT_RANDOM_HIGH-0}
      - TRANSMISSION_PEER_PORT_RANDOM_LOW=${TRANSMISSION_PEER_PORT_RANDOM_LOW-0}
      - TRANSMISSION_PEER_PORT_RANDOM_ON_START=${TRANSMISSION_PEER_PORT_RANDOM_ON_START-false}
      - TRANSMISSION_PORT_FORWARDING_ENABLED=${TRANSMISSION_PORT_FORWARDING_ENABLED-false}
      
      # Speed & Queue Settings
      - TRANSMISSION_ALT_SPEED_ENABLED=${TRANSMISSION_ALT_SPEED_ENABLED-false}
      - TRANSMISSION_ALT_SPEED_UP=${TRANSMISSION_ALT_SPEED_UP-0}
      - TRANSMISSION_ALT_SPEED_DOWN=${TRANSMISSION_ALT_SPEED_DOWN-0}
      - TRANSMISSION_SPEED_LIMIT_DOWN=${TRANSMISSION_SPEED_LIMIT_DOWN-0}
      - TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED=${TRANSMISSION_SPEED_LIMIT_DOWN_ENABLED-false}
      - TRANSMISSION_SPEED_LIMIT_UP=${TRANSMISSION_SPEED_LIMIT_UP-0}
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=${TRANSMISSION_SPEED_LIMIT_UP_ENABLED-false}
      - TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT=${TRANSMISSION_UPLOAD_SLOTS_PER_TORRENT-0}
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=${TRANSMISSION_DOWNLOAD_QUEUE_ENABLED-false}
      - TRANSMISSION_DOWNLOAD_QUEUE_SIZE=${TRANSMISSION_DOWNLOAD_QUEUE_SIZE-0}
      - TRANSMISSION_QUEUE_STALLED_ENABLED=${TRANSMISSION_QUEUE_STALLED_ENABLED-false}
      - TRANSMISSION_QUEUE_STALLED_MINUTES=${TRANSMISSION_QUEUE_STALLED_MINUTES-0}
      - TRANSMISSION_SEED_QUEUE_ENABLED=${TRANSMISSION_SEED_QUEUE_ENABLED-false}
      - TRANSMISSION_SEED_QUEUE_SIZE=${TRANSMISSION_SEED_QUEUE_SIZE-0}
      - TRANSMISSION_RATIO_LIMIT=${TRANSMISSION_RATIO_LIMIT-0}
      - TRANSMISSION_RATIO_LIMIT_ENABLED=${TRANSMISSION_RATIO_LIMIT_ENABLED-false}
      
      # RPC Settings
      - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=${TRANSMISSION_RPC_AUTHENTICATION_REQUIRED-false}
      - TRANSMISSION_RPC_BIND_ADDRESS=${TRANSMISSION_RPC_BIND_ADDRESS-0.0.0.0}
      - TRANSMISSION_RPC_ENABLED=${TRANSMISSION_RPC_ENABLED-true}
      - TRANSMISSION_RPC_HOST_WHITELIST=${TRANSMISSION_RPC_HOST_WHITELIST-}
      - TRANSMISSION_RPC_HOST_WHITELIST_ENABLED=${TRANSMISSION_RPC_HOST_WHITELIST_ENABLED-false}
      - TRANSMISSION_RPC_PORT=${TRANSMISSION_RPC_PORT-9091}
      - TRANSMISSION_RPC_URL=${TRANSMISSION_RPC_URL-}
      - TRANSMISSION_RPC_WHITELIST=${TRANSMISSION_RPC_WHITELIST-}
      - TRANSMISSION_RPC_WHITELIST_ENABLED=${TRANSMISSION_RPC_WHITELIST_ENABLED-false}
      
      # Additional Script & File Settings
      - TRANSMISSION_RENAME_PARTIAL_FILES=${TRANSMISSION_RENAME_PARTIAL_FILES-false}
      - TRANSMISSION_START_ADDED_TORRENTS=${TRANSMISSION_START_ADDED_TORRENTS-true}
      - TRANSMISSION_UMASK=${TRANSMISSION_UMASK-2}
      - TRANSMISSION_WATCH_DIR=${TRANSMISSION_WATCH_DIR-}
      - TRANSMISSION_WATCH_DIR_ENABLED=${TRANSMISSION_WATCH_DIR_ENABLED-false}
      - TRANSMISSION_CACHE_SIZE_MB=${TRANSMISSION_CACHE_SIZE_MB-0}
      - TRANSMISSION_DEFAULT_TRACKERS=${TRANSMISSION_DEFAULT_TRACKERS-}
      - TRANSMISSION_ENCRYPTION=${TRANSMISSION_ENCRYPTION-}
      - TRANSMISSION_MESSAGE_LEVEL=${TRANSMISSION_MESSAGE_LEVEL-0}
      - TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED=${TRANSMISSION_SCRAPE_PAUSED_TORRENTS_ENABLED-false}
      - TRANSMISSION_SCRIPT_TORRENT_ADDED_ENABLED=${TRANSMISSION_SCRIPT_TORRENT_ADDED_ENABLED-false}
      - TRANSMISSION_SCRIPT_TORRENT_ADDED_FILENAME=${TRANSMISSION_SCRIPT_TORRENT_ADDED_FILENAME-}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED=${TRANSMISSION_SCRIPT_TORRENT_DONE_ENABLED-false}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME=${TRANSMISSION_SCRIPT_TORRENT_DONE_FILENAME-}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_ENABLED=${TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_ENABLED-false}
      - TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_FILENAME=${TRANSMISSION_SCRIPT_TORRENT_DONE_SEEDING_FILENAME-}
      - TRANSMISSION_START_PAUSED=${TRANSMISSION_START_PAUSED-false}
      - TRANSMISSION_TCP_ENABLED=${TRANSMISSION_TCP_ENABLED-false}
      - TRANSMISSION_UTP_ENABLED=${TRANSMISSION_UTP_ENABLED-false}
      - TRANSMISSION_PREFERRED_TRANSPORT=${TRANSMISSION_PREFERRED_TRANSPORT-}
      
      # Alt Speed Time & Idle Seeding Settings
      - TRANSMISSION_ALT_SPEED_TIME_ENABLED=${TRANSMISSION_ALT_SPEED_TIME_ENABLED-false}
      - TRANSMISSION_ALT_SPEED_TIME_BEGIN=${TRANSMISSION_ALT_SPEED_TIME_BEGIN-}
      - TRANSMISSION_ALT_SPEED_TIME_END=${TRANSMISSION_ALT_SPEED_TIME_END-}
      - TRANSMISSION_ALT_SPEED_TIME_DAY=${TRANSMISSION_ALT_SPEED_TIME_DAY-0}
      - TRANSMISSION_IDLE_SEEDING_LIMIT=${TRANSMISSION_IDLE_SEEDING_LIMIT-0}
      - TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED=${TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED-false}
      
      # Bind Address Settings
      - TRANSMISSION_BIND_ADDRESS_IPV4=${TRANSMISSION_BIND_ADDRESS_IPV4-0.0.0.0}
      - TRANSMISSION_BIND_ADDRESS_IPV6=${TRANSMISSION_BIND_ADDRESS_IPV6-::}
      
      # Blocklist settings (already present)
      - TRANSMISSION_BLOCKLIST_ENABLED=${TRANSMISSION_BLOCKLIST_ENABLED-true}
      - TRANSMISSION_BLOCKLIST_URL=${TRANSMISSION_BLOCKLIST_URL-http://list.iblocklist.com/?list=bt_level1&fileformat=p2p&archiveformat=gz}

    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/custom:/etc/openvpn/custom
      - ${ROOT_FOLDER_HOST}/media/torrents:/media/torrents
    ports:
      - ${APP_PORT}:9091
    restart: unless-stopped
    networks:
      - tipi_main_network
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    logging:
      driver: json-file
      options:
        max-size: 10m
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.transmission-web-redirect.redirectscheme.scheme: https
      traefik.http.services.transmission.loadbalancer.server.scheme: http
      traefik.http.services.transmission.loadbalancer.server.port: 9091
      # Web
      traefik.http.routers.transmission-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.transmission-insecure.entrypoints: web
      traefik.http.routers.transmission-insecure.service: transmission
      traefik.http.routers.transmission-insecure.middlewares: transmission-web-redirect
      # Websecure
      traefik.http.routers.transmission.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.transmission.entrypoints: websecure
      traefik.http.routers.transmission.service: transmission
      traefik.http.routers.transmission.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.transmission-local-insecure.rule: Host(`transmission.${LOCAL_DOMAIN}`)
      traefik.http.routers.transmission-local-insecure.entrypoints: web
      traefik.http.routers.transmission-local-insecure.service: transmission
      traefik.http.routers.transmission-local-insecure.middlewares: transmission-web-redirect
      # Local domain secure
      traefik.http.routers.transmission-local.rule: Host(`transmission.${LOCAL_DOMAIN}`)
      traefik.http.routers.transmission-local.entrypoints: websecure
      traefik.http.routers.transmission-local.service: transmission
      traefik.http.routers.transmission-local.tls: true
      runtipi.managed: true
