services:
  nextcloud-aio-mastercontainer:
    container_name: nextcloud-aio-mastercontainer
    image: nextcloud/all-in-one:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=0.0.0.0
      - SKIP_DOMAIN_VALIDATION=false
      - NEXTCLOUD_ADDITIONAL_APKS=imagemagick
      - NEXTCLOUD_ADDITIONAL_PHP_EXTENSIONS=imagick
      - NEXTCLOUD_ENABLE_NVIDIA_GPU=true
    volumes:
      - ${APP_DATA_DIR}/data/docker-aio-config:/mnt/docker-aio-config
    ports:
      - ${APP_PORT}:8080
      - 8443:8443
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.nextcloud-aio-mastercontainer-web-redirect.redirectscheme.scheme: https
      traefik.http.services.nextcloud-aio-mastercontainer.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.nextcloud-aio-mastercontainer-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextcloud-aio-mastercontainer-insecure.entrypoints: web
      traefik.http.routers.nextcloud-aio-mastercontainer-insecure.service: nextcloud-aio-mastercontainer
      traefik.http.routers.nextcloud-aio-mastercontainer-insecure.middlewares: nextcloud-aio-mastercontainer-web-redirect
      # Websecure
      traefik.http.routers.nextcloud-aio-mastercontainer.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.nextcloud-aio-mastercontainer.entrypoints: websecure
      traefik.http.routers.nextcloud-aio-mastercontainer.service: nextcloud-aio-mastercontainer
      traefik.http.routers.nextcloud-aio-mastercontainer.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.nextcloud-aio-mastercontainer-local-insecure.rule: Host(`nextcloud-aio-mastercontainer.${LOCAL_DOMAIN}`)
      traefik.http.routers.nextcloud-aio-mastercontainer-local-insecure.entrypoints: web
      traefik.http.routers.nextcloud-aio-mastercontainer-local-insecure.service: nextcloud-aio-mastercontainer
      traefik.http.routers.nextcloud-aio-mastercontainer-local-insecure.middlewares: nextcloud-aio-mastercontainer-web-redirect
      # Local domain secure
      traefik.http.routers.nextcloud-aio-mastercontainer-local.rule: Host(`nextcloud-aio-mastercontainer.${LOCAL_DOMAIN}`)
      traefik.http.routers.nextcloud-aio-mastercontainer-local.entrypoints: websecure
      traefik.http.routers.nextcloud-aio-mastercontainer-local.service: nextcloud-aio-mastercontainer
      traefik.http.routers.nextcloud-aio-mastercontainer-local.tls: true
      runtipi.managed: true
